export { default as image1 } from "./1.png";
export { default as image10, default as image12 } from "./10.png";
export { default as image11 } from "./11.png";
export { default as image2 } from "./2.png";
export { default as image3 } from "./3.png";
export { default as image4 } from "./4.png";
export { default as image5 } from "./5.png";
export { default as image6 } from "./6.png";
export { default as image7 } from "./7.png";
export { default as image8 } from "./8.png";
export { default as image9 } from "./9.png";
